// civics.js - Official USCIS 100 Civics Questions (2008 version, current as of 2026)
// Source: uscis.gov/citizenship/find-study-materials-and-resources/study-for-the-test/100-civics-questions-and-answers
export const CIVICS_QUESTIONS = [
  // A: Principles of American Democracy
  { id:1, cat:"American Government", q:"What is the supreme law of the land?", a:["the Constitution"] },
  { id:2, cat:"American Government", q:"What does the Constitution do?", a:["sets up the government","defines the government","protects basic rights of Americans"] },
  { id:3, cat:"American Government", q:"The idea of self-government is in the first three words of the Constitution. What are these words?", a:["We the People"] },
  { id:4, cat:"American Government", q:"What is an amendment?", a:["a change (to the Constitution)","an addition (to the Constitution)"] },
  { id:5, cat:"American Government", q:"What do we call the first ten amendments to the Constitution?", a:["the Bill of Rights"] },
  { id:6, cat:"American Government", q:"What is one right or freedom from the First Amendment?", a:["speech","religion","assembly","press","petition the government"] },
  { id:7, cat:"American Government", q:"How many amendments does the Constitution have?", a:["twenty-seven (27)"] },
  { id:8, cat:"American Government", q:"What did the Declaration of Independence do?", a:["announced our independence (from Great Britain)","declared our independence (from Great Britain)","said that the United States is free (from Great Britain)"] },
  { id:9, cat:"American Government", q:"What are two rights in the Declaration of Independence?", a:["life","liberty","pursuit of happiness"] },
  { id:10, cat:"American Government", q:"What is freedom of religion?", a:["You can practice any religion, or not practice a religion."] },
  { id:11, cat:"American Government", q:"What is the economic system in the United States?", a:["capitalist economy","market economy"] },
  { id:12, cat:"American Government", q:"What is the \"rule of law\"?", a:["Everyone must follow the law.","Leaders must obey the law.","Government must obey the law.","No one is above the law."] },
  // B: System of Government
  { id:13, cat:"System of Government", q:"Name one branch or part of the government.", a:["Congress","legislative","President","executive","the courts","judicial"] },
  { id:14, cat:"System of Government", q:"What stops one branch of government from becoming too powerful?", a:["checks and balances","separation of powers"] },
  { id:15, cat:"System of Government", q:"Who is in charge of the executive branch?", a:["the President"] },
  { id:16, cat:"System of Government", q:"Who makes federal laws?", a:["Congress","Senate and House (of Representatives)","(U.S. or national) legislature"] },
  { id:17, cat:"System of Government", q:"What are the two parts of the U.S. Congress?", a:["the Senate and House (of Representatives)"] },
  { id:18, cat:"System of Government", q:"How many U.S. Senators are there?", a:["one hundred (100)"] },
  { id:19, cat:"System of Government", q:"We elect a U.S. Senator for how many years?", a:["six (6)"] },
  { id:20, cat:"System of Government", q:"Who is one of your state's U.S. Senators now?", a:["Answers will vary. (Residents of U.S. territories should say their territory has no U.S. Senators.) Look up your state at senate.gov."] },
  { id:21, cat:"System of Government", q:"The House of Representatives has how many voting members?", a:["four hundred thirty-five (435)"] },
  { id:22, cat:"System of Government", q:"We elect a U.S. Representative for how many years?", a:["two (2)"] },
  { id:23, cat:"System of Government", q:"Name your U.S. Representative.", a:["Answers will vary. Look up at house.gov."] },
  { id:24, cat:"System of Government", q:"Who does a U.S. Senator represent?", a:["all people of the state"] },
  { id:25, cat:"System of Government", q:"Why do some states have more Representatives than other states?", a:["(because of) the state's population","(because) they have more people","(because) some states have more people"] },
  { id:26, cat:"System of Government", q:"We elect a President for how many years?", a:["four (4)"] },
  { id:27, cat:"System of Government", q:"In what month do we vote for President?", a:["November"] },
  { id:28, cat:"System of Government", q:"What is the name of the President of the United States now?", a:["Check whitehouse.gov for the current President."] },
  { id:29, cat:"System of Government", q:"What is the name of the Vice President of the United States now?", a:["Check whitehouse.gov for the current Vice President."] },
  { id:30, cat:"System of Government", q:"If the President can no longer serve, who becomes President?", a:["the Vice President"] },
  { id:31, cat:"System of Government", q:"If both the President and the Vice President can no longer serve, who becomes President?", a:["the Speaker of the House"] },
  { id:32, cat:"System of Government", q:"Who is the Commander in Chief of the military?", a:["the President"] },
  { id:33, cat:"System of Government", q:"Who signs bills to become laws?", a:["the President"] },
  { id:34, cat:"System of Government", q:"Who vetoes bills?", a:["the President"] },
  { id:35, cat:"System of Government", q:"What does the President's Cabinet do?", a:["advises the President"] },
  { id:36, cat:"System of Government", q:"What are two Cabinet-level positions?", a:["Secretary of Agriculture","Secretary of Commerce","Secretary of Defense","Secretary of Education","Secretary of Energy","Secretary of Health and Human Services","Secretary of Homeland Security","Secretary of Housing and Urban Development","Secretary of the Interior","Secretary of Labor","Secretary of State","Secretary of Transportation","Secretary of the Treasury","Secretary of Veterans Affairs","Attorney General","Vice President"] },
  { id:37, cat:"System of Government", q:"What does the judicial branch do?", a:["reviews laws","explains laws","resolves disputes (disagreements)","decides if a law goes against the Constitution"] },
  { id:38, cat:"System of Government", q:"What is the highest court in the United States?", a:["the Supreme Court"] },
  { id:39, cat:"System of Government", q:"How many justices are on the Supreme Court?", a:["nine (9)"] },
  { id:40, cat:"System of Government", q:"Who is the Chief Justice of the United States now?", a:["John Roberts (John G. Roberts, Jr.)"] },
  { id:41, cat:"System of Government", q:"Under our Constitution, some powers belong to the federal government. What is one power of the federal government?", a:["to print money","to declare war","to create an army","to make treaties"] },
  { id:42, cat:"System of Government", q:"Under our Constitution, some powers belong to the states. What is one power of the states?", a:["provide schooling and education","provide protection (police)","provide safety (fire departments)","give a driver's license","approve zoning and land use"] },
  { id:43, cat:"System of Government", q:"Who is the Governor of your state now?", a:["Answers will vary. Residents of D.C. and U.S. territories without a Governor should say \"we don't have a Governor.\""] },
  { id:44, cat:"System of Government", q:"What is the capital of your state?", a:["Answers will vary. For D.C., the answer is that D.C. is not a state and does not have a capital. Residents of U.S. territories should name the capital of the territory."] },
  { id:45, cat:"System of Government", q:"What are the two major political parties in the United States?", a:["Democratic and Republican"] },
  { id:46, cat:"System of Government", q:"What is the political party of the President now?", a:["Check whitehouse.gov for current information."] },
  { id:47, cat:"System of Government", q:"What is the name of the Speaker of the House of Representatives now?", a:["Check house.gov for current information."] },
  // C: Rights and Responsibilities
  { id:48, cat:"Rights & Responsibilities", q:"There are four amendments to the Constitution about who can vote. Describe one of them.", a:["Citizens eighteen (18) and older (can vote).","You don't have to pay (a poll tax) to vote.","Any citizen can vote. (Women and men can vote.)","A male citizen of any race (can vote)."] },
  { id:49, cat:"Rights & Responsibilities", q:"What is one responsibility that is only for United States citizens?", a:["serve on a jury","vote in a federal election"] },
  { id:50, cat:"Rights & Responsibilities", q:"Name one right only for United States citizens.", a:["vote in a federal election","run for federal office"] },
  { id:51, cat:"Rights & Responsibilities", q:"What are two rights of everyone living in the United States?", a:["freedom of expression","freedom of speech","freedom of assembly","freedom to petition the government","freedom of religion","the right to bear arms"] },
  { id:52, cat:"Rights & Responsibilities", q:"What do we show loyalty to when we say the Pledge of Allegiance?", a:["the United States","the flag"] },
  { id:53, cat:"Rights & Responsibilities", q:"What is one promise you make when you become a United States citizen?", a:["give up loyalty to other countries","defend the Constitution and laws of the United States","obey the laws of the United States","serve in the U.S. military (if needed)","serve (do important work for) the nation (if needed)","be loyal to the United States"] },
  { id:54, cat:"Rights & Responsibilities", q:"How old do citizens have to be to vote for President?", a:["eighteen (18) and older"] },
  { id:55, cat:"Rights & Responsibilities", q:"What are two ways that Americans can participate in their democracy?", a:["vote","join a political party","help with a campaign","join a civic group","join a community group","give an elected official your opinion on an issue","call Senators and Representatives","publicly support or oppose an issue or policy","run for office","write to a newspaper"] },
  { id:56, cat:"Rights & Responsibilities", q:"When is the last day you can send in federal income tax forms?", a:["April 15"] },
  { id:57, cat:"Rights & Responsibilities", q:"When must all men register for the Selective Service?", a:["at age eighteen (18)","between eighteen (18) and twenty-six (26)"] },
  // AMERICAN HISTORY
  { id:58, cat:"American History", q:"What is one reason colonists came to America?", a:["freedom","political liberty","religious freedom","economic opportunity","practice their religion","escape persecution"] },
  { id:59, cat:"American History", q:"Who lived in America before the Europeans arrived?", a:["American Indians","Native Americans"] },
  { id:60, cat:"American History", q:"What group of people was taken to America and sold as slaves?", a:["Africans","people from Africa"] },
  { id:61, cat:"American History", q:"Why did the colonists fight the British?", a:["because of high taxes (taxation without representation)","because the British army stayed in their houses (boarding, quartering)","because they didn't have self-government"] },
  { id:62, cat:"American History", q:"Who wrote the Declaration of Independence?", a:["(Thomas) Jefferson"] },
  { id:63, cat:"American History", q:"When was the Declaration of Independence adopted?", a:["July 4, 1776"] },
  { id:64, cat:"American History", q:"There were 13 original states. Name three.", a:["New Hampshire","Massachusetts","Rhode Island","Connecticut","New York","New Jersey","Pennsylvania","Delaware","Maryland","Virginia","North Carolina","South Carolina","Georgia"] },
  { id:65, cat:"American History", q:"What happened at the Constitutional Convention?", a:["The Constitution was written.","The Founding Fathers wrote the Constitution."] },
  { id:66, cat:"American History", q:"When was the Constitution written?", a:["1787"] },
  { id:67, cat:"American History", q:"The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.", a:["(James) Madison","(Alexander) Hamilton","(John) Jay","Publius"] },
  { id:68, cat:"American History", q:"What is one thing Benjamin Franklin is famous for?", a:["U.S. diplomat","oldest member of the Constitutional Convention","first Postmaster General of the United States","writer of \"Poor Richard's Almanac\"","started the first free libraries"] },
  { id:69, cat:"American History", q:"Who is the \"Father of Our Country\"?", a:["(George) Washington"] },
  { id:70, cat:"American History", q:"Who was the first President?", a:["(George) Washington"] },
  { id:71, cat:"American History", q:"What territory did the United States buy from France in 1803?", a:["the Louisiana Territory","Louisiana"] },
  { id:72, cat:"American History", q:"Name one war fought by the United States in the 1800s.", a:["War of 1812","Mexican-American War","Civil War","Spanish-American War"] },
  { id:73, cat:"American History", q:"Name the U.S. war between the North and the South.", a:["the Civil War","the War between the States"] },
  { id:74, cat:"American History", q:"Name one problem that led to the Civil War.", a:["slavery","economic reasons","states' rights"] },
  { id:75, cat:"American History", q:"What was one important thing that Abraham Lincoln did?", a:["freed the slaves (Emancipation Proclamation)","saved (or preserved) the Union","led the United States during the Civil War"] },
  { id:76, cat:"American History", q:"What did the Emancipation Proclamation do?", a:["freed the slaves","freed slaves in the Confederacy","freed slaves in the Confederate states","freed slaves in most Southern states"] },
  { id:77, cat:"American History", q:"What did Susan B. Anthony do?", a:["fought for women's rights","fought for civil rights"] },
  { id:78, cat:"American History", q:"Name one war fought by the United States in the 1900s.", a:["World War I","World War II","Korean War","Vietnam War","(Persian) Gulf War"] },
  { id:79, cat:"American History", q:"Who was President during World War I?", a:["(Woodrow) Wilson"] },
  { id:80, cat:"American History", q:"Who was President during the Great Depression and World War II?", a:["(Franklin) Roosevelt"] },
  { id:81, cat:"American History", q:"Who did the United States fight in World War II?", a:["Japan, Germany, and Italy"] },
  { id:82, cat:"American History", q:"Before he was President, Eisenhower was a general. What war was he in?", a:["World War II"] },
  { id:83, cat:"American History", q:"During the Cold War, what was the main concern of the United States?", a:["Communism"] },
  { id:84, cat:"American History", q:"What movement tried to end racial discrimination?", a:["civil rights (movement)"] },
  { id:85, cat:"American History", q:"What did Martin Luther King, Jr. do?", a:["fought for civil rights","worked for equality for all Americans"] },
  { id:86, cat:"American History", q:"What major event happened on September 11, 2001, in the United States?", a:["Terrorists attacked the United States."] },
  { id:87, cat:"American History", q:"Name one American Indian tribe in the United States.", a:["Cherokee","Navajo","Sioux","Chippewa","Choctaw","Pueblo","Apache","Iroquois","Creek","Blackfeet","Seminole","Cheyenne","Arawak","Shawnee","Mohegan","Huron","Oneida","Lakota","Crow","Teton","Hopi","Inuit"] },
  // INTEGRATED CIVICS
  { id:88, cat:"Geography", q:"Name one of the two longest rivers in the United States.", a:["Missouri (River)","Mississippi (River)"] },
  { id:89, cat:"Geography", q:"What ocean is on the West Coast of the United States?", a:["Pacific (Ocean)"] },
  { id:90, cat:"Geography", q:"What ocean is on the East Coast of the United States?", a:["Atlantic (Ocean)"] },
  { id:91, cat:"Geography", q:"Name one U.S. territory.", a:["Puerto Rico","U.S. Virgin Islands","American Samoa","Northern Mariana Islands","Guam"] },
  { id:92, cat:"Geography", q:"Name one state that borders Canada.", a:["Maine","New Hampshire","Vermont","New York","Pennsylvania","Ohio","Michigan","Minnesota","North Dakota","Montana","Idaho","Washington","Alaska"] },
  { id:93, cat:"Geography", q:"Name one state that borders Mexico.", a:["California","Arizona","New Mexico","Texas"] },
  { id:94, cat:"Geography", q:"What is the capital of the United States?", a:["Washington, D.C."] },
  { id:95, cat:"Geography", q:"Where is the Statue of Liberty?", a:["New York (Harbor)","Liberty Island","New Jersey","near New York City","on the Hudson (River)"] },
  { id:96, cat:"Symbols", q:"Why does the flag have 13 stripes?", a:["because there were 13 original colonies","because the stripes represent the original colonies"] },
  { id:97, cat:"Symbols", q:"Why does the flag have 50 stars?", a:["because there is one star for each state","because each star represents a state","because there are 50 states"] },
  { id:98, cat:"Symbols", q:"What is the name of the national anthem?", a:["The Star-Spangled Banner"] },
  { id:99, cat:"Holidays", q:"When do we celebrate Independence Day?", a:["July 4"] },
  { id:100, cat:"Holidays", q:"Name two national U.S. holidays.", a:["New Year's Day","Martin Luther King, Jr. Day","Presidents' Day","Memorial Day","Juneteenth","Independence Day","Labor Day","Columbus Day","Veterans Day","Thanksgiving","Christmas"] }
];

// Common N-400 Interview Questions
export const N400_QUESTIONS = [
  { q:"What is your full name?", tip:"Say your complete legal name as on your application." },
  { q:"Have you used any other names?", tip:"List maiden names, nicknames, or aliases." },
  { q:"What is your date of birth?", tip:"Give the full date: month, day, year." },
  { q:"Where were you born?", tip:"Name the city and country." },
  { q:"Where do you currently live?", tip:"Give your full home address." },
  { q:"How long have you lived at your current address?", tip:"Answer in years and months." },
  { q:"Are you a U.S. citizen?", tip:"Answer 'No, I am a lawful permanent resident.'" },
  { q:"When did you become a permanent resident?", tip:"Give the date on your green card." },
  { q:"What is your A-number?", tip:"Your Alien Registration Number from your green card." },
  { q:"What is your marital status?", tip:"Single, married, divorced, or widowed." },
  { q:"Do you have any children?", tip:"Be ready to give names and ages." },
  { q:"What do you do for a living?", tip:"Describe your job or employer." },
  { q:"Have you ever been arrested?", tip:"Answer truthfully. Disclose any arrests even if charges were dropped." },
  { q:"Have you ever been a member of the Communist Party?", tip:"Answer truthfully." },
  { q:"Do you support the Constitution and form of government of the United States?", tip:"Answer 'Yes.'" },
  { q:"Are you willing to take the full Oath of Allegiance?", tip:"Answer 'Yes.'" },
  { q:"Why do you want to become a U.S. citizen?", tip:"Personal answer — freedom, voting, family, opportunity." },
  { q:"Who is the President of the United States?", tip:"Civics question — see test material." },
  { q:"What is the Constitution?", tip:"The supreme law of the land." },
  { q:"What are the colors of our flag?", tip:"Red, white, and blue." }
];

// Reading & Writing test vocabulary (USCIS official lists)
export const READING_SENTENCES = [
  "Who is the President of the United States?",
  "What are the colors of the flag?",
  "When do we vote for President?",
  "Where does the President live?",
  "Why do people come to America?",
  "Name one state that borders Canada.",
  "What is the capital of the United States?",
  "Name one right of Americans.",
  "Who was Abraham Lincoln?",
  "Who was the first President?"
];

export const WRITING_SENTENCES = [
  "The President lives in the White House.",
  "Citizens can vote.",
  "Lincoln was the President during the Civil War.",
  "The flag has 50 stars.",
  "Memorial Day is in May.",
  "Independence Day is in July.",
  "Washington is the Father of Our Country.",
  "We vote for the President in November.",
  "The United States has fifty states.",
  "Alaska is the largest state."
];
